#################### DEMO 1

spring:
  cloud:
    gateway:
      routes:
        - id: route1
          uri: https://httpbin.org
          predicates:
            - Path=/uuid

# Show a basic path predicate routing to a destination uri

# Test:
# curl httpbin.org/uuid
# curl localhost:8080/uuid

# With http default formatted output:
# http localhost:8080/uuid
# http :8080/uuid --verbose
