spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      metrics:
        enabled: true   # default value
      actuator:
        verbose:
          enabled: true   # see /actuator/gateway/routes

management:
  endpoint:
    gateway:
      enabled: true       # default value
  endpoints:
    web:
      exposure:
        include: "*"        # OR include: gateway
  health:
    redis:
      enabled: false      # because redis starter is in pom... change to true to use redis rate limiting